title: 鏡花緣 - 吳淡如
description: 鏡花緣 - 吳淡如
time: Mon, 26 Aug 2024 02:55:30 +0000
items:
  - title: 00. 前言─序─鏡中花、水中月
    size: 4996328
    duration: 312
  - title: 01. 第一章─一切的開端
    size: 12970571
    duration: 810
  - title: 02. 第一章─出海遠遊
    size: 22215410
    duration: 1388
  - title: 03. 第一章─君子國
    size: 15022751
    duration: 938
  - title: 04. 第二章─大人國見聞
    size: 27553585
    duration: 1722
  - title: 05. 第二章─小人國 人如三寸丁
    size: 22584468
    duration: 1411
  - title: 06. 第二章─遇險被救訪舊友
    size: 28278326
    duration: 1767
  - title: 07. 第三章─ 林之洋 女兒國裡當王妃
    size: 25640168
    duration: 1602
  - title: 08. 第三章─蓬萊仙島
    size: 29910875
    duration: 1869
  - title: 09. 第三章─待字閨中的臣子
    size: 26653301
    duration: 1665
  - title: 10. 第四章─百花仙子齊聚一堂
    size: 22236308
    duration: 1389
  - title: 11. 第四章─歷遍繁華棄世成仙
    size: 20267592
    duration: 1266
  - title: 12. 後記1─我看李汝珍
    size: 6458412
    duration: 403
  - title: 13. 後記2─關於武則天
    size: 16051348

    duration: 1003